const statuses = [
  // Informational
  { code: 100, message: 'Continue', type: 'Informational' },
  { code: 101, message: 'Switching Protocols', type: 'Informational' },
  { code: 102, message: 'Processing', type: 'Informational' },

  // Success
  { code: 200, message: 'Ok', type: 'Success' },
  { code: 201, message: 'Created', type: 'Success' },
  { code: 202, message: 'Accepted', type: 'Success' },
  { code: 203, message: 'Non Authoritative Information', type: 'Success' },
  { code: 204, message: 'No Content', type: 'Success' },
  { code: 205, message: 'Reset Content', type: 'Success' },
  { code: 206, message: 'Partial Content', type: 'Success' },
  { code: 207, message: 'Multi Status', type: 'Success' },
  { code: 208, message: 'Already Reported', type: 'Success' },
  { code: 226, message: 'Im Used', type: 'Success' },

  // Redirection
  { code: 300, message: 'Multiple Choices', type: 'Redirection' },
  { code: 301, message: 'Moved Permanently', type: 'Redirection' },
  { code: 302, message: 'Found', type: 'Redirection' },
  { code: 303, message: 'See Other', type: 'Redirection' },
  { code: 304, message: 'Not Modified', type: 'Redirection' },
  { code: 305, message: 'Use Proxy', type: 'Redirection' },
  { code: 307, message: 'Temporary Redirect', type: 'Redirection' },
  { code: 308, message: 'Permanent Redirect', type: 'Redirection' },

  // Client Error
  { code: 400, message: 'Bad Request', type: 'Client Error' },
  { code: 401, message: 'Unauthorized', type: 'Client Error' },
  { code: 402, message: 'Payment Required', type: 'Client Error' },
  { code: 403, message: 'Forbidden', type: 'Client Error' },
  { code: 404, message: 'Not Found', type: 'Client Error' },
  { code: 405, message: 'Method Not Allowed', type: 'Client Error' },
  { code: 406, message: 'Not Acceptable', type: 'Client Error' },
  { code: 407, message: 'Proxy Authentication Required', type: 'Client Error' },
  { code: 408, message: 'Request Timeout', type: 'Client Error' },
  { code: 409, message: 'Conflict', type: 'Client Error' },
  { code: 410, message: 'Gone', type: 'Client Error' },
  { code: 411, message: 'Length Required', type: 'Client Error' },
  { code: 412, message: 'Precondition Failed', type: 'Client Error' },
  { code: 413, message: 'Payload Too Large', type: 'Client Error' },
  { code: 414, message: 'Request URI Too Long', type: 'Client Error' },
  { code: 415, message: 'Unsupported Media Type', type: 'Client Error' },
  { code: 416, message: 'Requested Range Not Satisfiable', type: 'Client Error' },
  { code: 417, message: 'Expectation Failed', type: 'Client Error' },
  { code: 418, message: 'Im a teapot', type: 'Client Error' },
  { code: 421, message: 'Misdirected Request', type: 'Client Error' },
  { code: 422, message: 'Unprocessable Entity', type: 'Client Error' },
  { code: 423, message: 'Locked', type: 'Client Error' },
  { code: 424, message: 'Failed Dependency', type: 'Client Error' },
  { code: 426, message: 'Upgrade Required', type: 'Client Error' },
  { code: 428, message: 'Precondition Required', type: 'Client Error' },
  { code: 429, message: 'Too Many Requests', type: 'Client Error' },
  { code: 431, message: 'Request Header Fields Too Large', type: 'Client Error' },
  { code: 444, message: 'Connection Closed Without Response', type: 'Client Error' },
  { code: 451, message: 'Unavailable For Legal Reasons', type: 'Client Error' },
  { code: 499, message: 'Client Closed Request', type: 'Client Error' },

  // Server Error
  { code: 500, message: 'Internal Server Error', type: 'Server Error' },
  { code: 501, message: 'Not Implemented', type: 'Server Error' },
  { code: 502, message: 'Bad Gateway', type: 'Server Error' },
  { code: 503, message: 'Service Unavailable', type: 'Server Error' },
  { code: 504, message: 'Gateway Timeout', type: 'Server Error' },
  { code: 505, message: 'Http Version Not Supported', type: 'Server Error' },
  { code: 506, message: 'Variant Also Negotiates', type: 'Server Error' },
  { code: 507, message: 'Insufficient Storage', type: 'Server Error' },
  { code: 508, message: 'Loop Detected', type: 'Server Error' },
  { code: 510, message: 'Not Extended', type: 'Server Error' },
  { code: 511, message: 'Network Authentication Required', type: 'Server Error' },
  { code: 599, message: 'Network Connect Timeout Error', type: 'Server Error' }
]

module.exports = statuses
